language: node_js
node_js:
  - "lts/*"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn

cache:
  yarn: true

before_script:
  - yarn global add codecov
  - yarn setup
  - yarn build

script:
  - yarn test-ci

after_success:
  - codecov
  - yarn pack

deploy:
  - provider: releases
    edge: true
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "tick-knock-*.tgz"
    cleanup: false
    on:
      tags: true
  - provider: npm
    edge: true
    cleanup: false
    email: "contact@pastila.org"
    api_key: $NPM_TOKEN
    on:
      tags: true
